### ISSUE TITLE
INSTALL ERROR: ImportError: cannot import name which

### ISSUE THREAD

**Issue by dwightmulcahy** [rcarmo/piku#15]
fresh copy of Jessie 07-05 for Raspberry Pi... when I do `python piku.py setup` it gives me an import error.

```
piku@raspberrypi:~ $ python piku.py setup
Traceback (most recent call last):
  File "piku.py", line 16, in <module>
    from shutil import copyfile, rmtree, which
ImportError: cannot import name which
```

**Comment by rcarmo** [comment]
Make sure you follow the documentation to install it, and run it under python3.

**Comment by rcarmo** [comment]
Incidentally, if you’re using the most recent Raspbian, follow the Ubuntu 18 install instructions, since the package trees are now nearly at parity. I don’t use Raspbian myself on the Pi, but I’m told they work.

**Comment by dwightmulcahy** [comment]
can't really get it working with python3 either.  I get a more promising message this time but can't seem to get `click` installed for python3.  `pip` always installs it for 2.7.  :( 

```
piku@raspberrypi:~ $ python3 piku.py setup
Traceback (most recent call last):
  File "piku.py", line 5, in <module>
    from click import argument, command, group, get_current_context, option, secho as echo
ImportError: No module named 'click'
```

**Comment by dwightmulcahy** [comment]
FYI, the Ubuntu 18 instructions fail on the first command... 

```
pi@raspberrypi:~ $ sudo apt-get install -y build-essential certbot git incron \
>     libjpeg-dev libxml2-dev libxslt1-dev zlib1g-dev nginx \
>     python-certbot-nginx python-dev python-pip \
>     python-virtualenv python3-dev python3-pip python3-virtualenv \
>     uwsgi uwsgi-plugin-asyncio-python3 uwsgi-plugin-gevent-python \
>     uwsgi-plugin-python uwsgi-plugin-python3 uwsgi-plugin-tornado-python
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package certbot
E: Unable to locate package python-certbot-nginx
E: Unable to locate package uwsgi-plugin-asyncio-python3
E: Unable to locate package uwsgi-plugin-gevent-python
E: Unable to locate package uwsgi-plugin-tornado-python
```

**Comment by rcarmo** [comment]
Try sudo apt-get install python3-click. Dependencies on Raspbian might be different.

**Comment by dwightmulcahy** [comment]
thanks... got it working by other means... might do a PR to clean up the Raspberry PI install doc a bit.

**Comment by rcarmo** [comment]
I suggest copying the Ubuntu one and use it as base, it’s cleaner than the current Pi one...

**Comment by dwightmulcahy** [comment]
>  if you’re using the most recent Raspbian, follow the Ubuntu 18 install instructions

so are you suggesting installing Raspbian Stretch and using the `ubuntu-18.04-bionic.md` install instructions?

**Comment by rcarmo** [comment]
Yes. I've only tested on Stretch, and have it installed now using the Ubuntu doc. I'm going to copy it across so any PRs can refer to it.

**Comment by rcarmo** [comment]
I've tested this on Stretch with Python 3.5, and also added a version check to the start of the script, just to make sure...
