### ISSUE TITLE
deploying example gives "Invalid Procfile" on raspberry Pi

### ISSUE THREAD

**Issue by dwightmulcahy** [rcarmo/piku#19]
Ok... for grins I tried to pushing the python_example to my Piku setup on a raspberrypi.

I get an odd error `remote: Error: Invalid Procfile for app 'python_example'.`...

**_Where can I look to get more info on what is failing?_**

```
dwight : ~/piku/examples/python (master)
🍺 $ git push piku master
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 431 bytes | 215.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: -----> Deploying app 'python_example'
remote: Your branch is up-to-date with 'origin/master'.
remote: Error: Invalid Procfile for app 'python_example'.
To piku.local:python_example
   672e0fe..dabd96b  master -> master
```

the `Procfile`:
```
🍺 $ cat Procfile
wsgi: main:app
worker: python worker.py
```

no logs that would help... 
```
🍺 $ ssh piku@piku.local logs python_example
No logs found for app 'python_example'.
```

**Comment by rcarmo** [comment]
Logs are for running apps, not deployments. I’ll give this a whirl later to see if I can reproduce it with the example - my apps all have more complex Procfiles...

**Comment by rcarmo** [comment]
Well, I just tested it (see #20). I pushed the original `Procfile` first, then tested for #20, and both worked on a clean install on a Pi. No idea what might be wrong at your end.

**Comment by dwightmulcahy** [comment]
So I just tested this while creating a test for `APScheduler` and had this same thing occur.  I have a feeling that it maybe is extra spaces or newlines that causes this error message.  I'll try to recreate it and so that I can add the steps involved to get this error to occur.

**Comment by rcarmo** [comment]
It might be newlines in git if you're using Windows (I don't use Windows for development work myself). Check the CRLF settings.

**Comment by dwightmulcahy** [comment]
Using MacOS and PyCharm.  Typically will edit the `Procfile` with nano.  I'm going to save off the next `Procfile` that causes this issue and debug it to see where it is causing the failure.

This section seems to be the area that I'll be looking at in the `do_deploy` function:
```
        workers = parse_procfile(procfile)
        if workers and len(workers):
           ...
        else:
            echo("Error: Invalid Procfile for app '{}'.".format(app), fg='red')
```

I'm playing with a couple of different things so I should have an opportunity to see this again.

**Comment by dwightmulcahy** [comment]
So I haven't been able to reproduce this since it happened a couple of times to me.  

Closing this issue for now and if it occurs again I'll reproduce before opening this again.
