### ISSUE TITLE
`clock` type worker?

### ISSUE THREAD

**Issue by dwightmulcahy** [rcarmo/piku#20]
I'm needing to schedule a couple of weekly tasks to run, is using APScheduler a recommended way (https://devcenter.heroku.com/articles/clock-processes-python) or is there an easier way?

Looking at the code it looks like `web` and `wsgi` are the only ones that get processed and the rest are created as the tag name.

_sorry, fairly new to Heroku process types_

**Comment by rcarmo** [comment]
That’s not supported. All my recurring jobs simply sleep() or sleep() and exit() to get automatically restarted (that’s sometimes cleaner and frees up RAM on the Pi)

**Comment by rcarmo** [comment]
Well, as it happens I've tested it and since I don't do any special treatment of `clock`, it is actually working on my lab Pi. I've also tested #19, which works on a fresh install for me.

Thanks for pointing out the Heroku article, I now realize that by using `APScheduler` it is actually usable outside their environment.

**Comment by dwightmulcahy** [comment]
Yeah, I put together an example using `APScheduler` and it works pretty well.

using this `Procfile`
```
web: python main.py
worker: python worker.py
clock: python clock.py
```

Using `APScheduler` in `clock.py` to schedule some tasks and it works like a charm.

**Comment by rcarmo** [comment]
Hi there!

Just a quick note to say that we now have a `cron` worker that does away with the need for the processes to self-schedule (`uwsgi` can take simple `cron` patterns, so I hacked that in today).

**Comment by chr15m** [comment]
Cool feature @rcarmo!

**Comment by rcarmo** [comment]
TBH, I have no idea if it’s been around for ever or a new `uwsgi` feature in the later versions. Stumbled upon it by accident when looking up something else...

**Comment by dwightmulcahy** [comment]
nice... have to try that out this weekend... will simplify regularly running tasks.

dWiGhT
