### ISSUE TITLE
`ps:scale` missing user documentation

### ISSUE THREAD

**Issue by dwightmulcahy** [rcarmo/piku#21]
Notice this in the code but ~no~ minimal mention of it in the docs.  (i.e. "scale up/down worker processes (ps:scale) at will.")
```
@piku.command("ps:scale")
@argument('app')
@argument('settings', nargs=-1)
```

the `piku.py` help shows (somewhat incorrectly?):
`  ps:scale          Show application configuration`

It should be showing that this takes arg(s) that specify the number to scale each type to.

This was what I was able to do to scale up the `worker` type processes (I have `piku` as an alias)
`piku ps:scale test worker=2`

**Comment by rcarmo** [comment]
Done. Feel free to suggest tweaks, it can probably look nicer.

**Comment by dwightmulcahy** [comment]
I think the additions you added are spot on.
