### ISSUE TITLE
Allow pushing of non-master branches

### ISSUE THREAD

**Issue by chr15m** [rcarmo/piku#22]
Hello, thanks for this fantastic project @rcarmo! I just successfully deployed my first piku instance. :tada: 

I'm about to issue a PR for something else but I wanted to write this down here while I can as it surprised me. I tried to push a non-master branch to my piku instance and nothing happened whereas on other PaaS this is not a problem and the app deploys as expected.

**Comment by rcarmo** [comment]
Yeah, well, that’s due to the very minimalist design. You can work around that by pushing that branch explicitly as master (I forget the right incantations, but I’ve done it).

**Comment by rcarmo** [comment]
Here you go [Stackoverflow has this neatly presented answer](https://stackoverflow.com/questions/5423517/how-do-i-push-a-local-git-branch-to-master-branch-in-the-remote). 

Right now I don't intend to implement this myself, but I will leave this opened in case there's a PR to address it :wink:

**Comment by dwightmulcahy** [comment]
Have you tired `git push piku yourbranch:master`?

**Comment by chr15m** [comment]
Thank you! BTW I consider the minimalist design a major feature.

**Comment by rcarmo** [comment]
Just noticed that I had a [TODO](https://github.com/rcarmo/piku/blob/8307dafa86cf02181776350b5ade00ab2cb5d378/piku.py#L1094) for it...
