### ISSUE TITLE
Pushing update to example app does not seem to change running version

### ISSUE THREAD

**Issue by chr15m** [rcarmo/piku#27]
I've pushed the example in `examples/python/` to my piku instance and it works great. The only change I made was to add the variable `NGINX_SERVER_NAME` so that I know where to see the result.

However, when I modified `main.py` and changed the output tables to add some random text I noticed that the text does not show up in the page after I commit and push to piku/master again. Looking at the logs it does not seem like uwsgi is restarting the server. What should I look for to diagnose this, or is it expected behaviour?

**Comment by chr15m** [comment]
root@piku:~# /usr/local/bin/uwsgi --version
2.0.15

Here's the log from a different app (which has the same issue) starting up:
```
web.1 | your processes number limit is 3898
web.1 | your memory page size is 4096 bytes
web.1 | detected max file descriptor number: 1024
web.1 | lock engine: pthread robust mutexes
web.1 | thunder lock: disabled (you can enable it with --thunder-lock)
web.1 | Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
web.1 | Set PythonHome to /home/piku/.piku/envs/test
web.1 | Python main interpreter initialized at 0x73b4f0
web.1 | python threads support enabled
web.1 | your mercy for graceful operations on workers is 60 seconds
web.1 | *** Operational MODE: no-workers ***
web.1 | spawned uWSGI master process (pid: 19777)
web.1 | [uwsgi-daemons] spawning "python app.py" (uid: 1000 gid: 33)
web.1 |  * Serving Flask app "app" (lazy loading)
web.1 |  * Environment: production
web.1 |    WARNING: This is a development server. Do not use it in a production deployment.
web.1 |    Use a production WSGI server instead.
web.1 |  * Debug mode: off
web.1 |  * Running on http://127.0.0.1:8112/ (Press CTRL+C to quit)
```

If I push any changes to `app.py` on that app the server does not restart.

**Comment by rcarmo** [comment]
It's expected. That's why there is a restart command, so that you don't break a running app by changing running code until all the workers are ready.

**Comment by rcarmo** [comment]
As an example, this is how I deploy my website (sometimes destructively when there are major changes to static files):

```Makefile
restart-production:
	ssh piku@$(PRODUCTION_SERVER) restart sushy

deploy-production:
	git push production master

reset-production:
	ssh piku@$(PRODUCTION_SERVER) destroy sushy

redeploy: reset-production deploy-production restart-production

deploy: deploy-production restart-production
	ssh piku@$(PRODUCTION_SERVER) logs sushy
```

**Comment by chr15m** [comment]
Ok, understood.

As a user I would expect your final makefile rule (deploy & restart) to be the default, and that's the default case on other PaaS I think.

> don't break a running app by changing running code until all the workers are ready

I'm confused about when/why this would happen. In what situation would deploy-and-immediately-restart fail?

**Comment by chr15m** [comment]
Oh, I thought of something - maybe sometimes you are just updating front-end files like JS and CSS and don't want to restart the workers in that case. Is that correct?

**Comment by rcarmo** [comment]
That and making sure dependencies get installed.

**Comment by chr15m** [comment]
Ah ok. I thought dependencies were completely installed during `git push production master` phase. Is there something that continues on after the push that you need to wait for before running the restart?

Sorry for all the questions just trying to wrap my head around this.

**Comment by chr15m** [comment]
@rcarmo thanks for merging #34 which solves the problem for me. Do you mind if I close this issue?

**Comment by rcarmo** [comment]
Feel free. I’m not going to do much coding today...
