### ISSUE TITLE
git remote show piku throws a traceback

### ISSUE THREAD

**Issue by chr15m** [rcarmo/piku#44]
```
$ git remote show piku
Usage: piku.py [OPTIONS] COMMAND [ARGS]...
Try "piku.py --help" for help.

Error: No such command "git-upload-pack".
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Would be good to pass some of the basic git commands through.

**Comment by rcarmo** [comment]
Feel free to do so. I’m very happy with what you’ve been contributing (especially given that I currently lack the time to add new functionality), and your use cases bring a new viewpoint that I lack (this was originally written to scratch my own itches).

**Comment by chr15m** [comment]
@rcarmo :+1: thanks, will do. I was really happy to find piku. I had been looking for something exactly like this for a while. I'll try to keep my contributions to the minimal philosophy you've established - it is a big reason why I was drawn to the project.

**Comment by dwightmulcahy** [comment]
I second that!  It has become pretty useful to me lately.
