### ISSUE TITLE
install python3.6

### ISSUE THREAD

**Issue by dwightmulcahy** [rcarmo/piku#53]
recently started using a f-strings in a project and pushed it to piku and noticed that is was giving syntax errors.  python3.5.3 installed.  

would it causes issues to install 3.6?

**Comment by rcarmo** [comment]
Depends. If you use uwsgi as a system package, you will need to recompile that to match your Python version or just use a Python web server and the web worker instead of wsgi.

If you’re using Raspbian, I’m currently planning to test Buster ASAP and note any differences.

**Comment by dwightmulcahy** [comment]
ok... so I installed python 3.7.2 and compiled a plugin for uwsgi.  Had to add a bit of code to `piku.py` but it seems to be running fine.  Thanks!

**Comment by dwightmulcahy** [comment]
This can be closed.  I'll move the info on what I changed to make this happen into issue #24.
