### ISSUE TITLE
"social preview" can use new logo

### ISSUE THREAD

**Issue by chr15m** [rcarmo/piku#61]
@rcarmo if you go into settings you can add the new logo to the "social preview":

![image](https://user-images.githubusercontent.com/67130/61177846-a71f1e00-a611-11e9-8cc3-78bc0b16fdfe.png)

This means when `github.com/rcarmo/piku` gets shared on Twitter or  other social media the logo will show up. Small thing but I think it helps with marketing.

**Comment by chr15m** [comment]
The new logo itself can be found in `img/logo.png` (just to save you digging around).

**Comment by rcarmo** [comment]
Ah, good catch, thanks.
