### ISSUE TITLE
Binaries on linux(Ubuntu)

### ISSUE THREAD

**Issue by matrixjnr** [rcarmo/piku#64]
It is probably good if you use the virtualenv from Ubuntu repository during installation.
I also noticed that piku's check_requirements(binaries) does not recognize binaries that are exported on the .bashrc file.

So install whatever you need using package manager.

```bash
$sudo apt-get install virtualenv maven nodejs etc.
```

**Comment by chr15m** [comment]
That's good to know. The `piku-bootstrap` script installs virtually in the way you suggest:

https://github.com/rcarmo/piku/blob/master/piku-bootstrap#L95

I have a patch to it and a bunch of modular playbooks for installing components like nodejs in a standardised way which I'll create a PR for.
