### ISSUE TITLE
ruby on rails

### ISSUE THREAD

**Issue by jbd0101** [rcarmo/piku#8]
Hello ,
I congratulate you on your work.
But I have a question to which I have no answer: can we use ruby on rails?

thank you
Jbd

**Comment by rcarmo** [comment]
If you mean if piku supports Ruby or Rails applications, then no, and I have no plans to support Ruby.

**Comment by pkoch** [comment]
What would it take to add support? Any pointers for enterprising souls?

**Comment by rcarmo** [comment]
Well, the Ruby plugin seems to be there: 

https://uwsgi-docs.readthedocs.io/en/latest/Ruby.html

...I don’t have a laptop handy to see if Ubuntu/Debian packages include the uwsgi Ruby plugin, but theoretically you should be able to get things going easily as long as you can use it.

If not, running a Ruby/Rack/etc web server as a stand-alone process is possible already (but undocumented)

**Comment by pkoch** [comment]
Got it! Thanks for the pointers!

I intend to give piku a try for deploying some rails apps when my pi
arrives. I'll report more stuff once I get my hands dirty.
